version: 2.1

orbs:
    welcome: circleci/welcome-orb@0.4.1

jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10.18.1
        steps:
            - checkout
            - run:
                  name: 'Update NPM'
                  command: sudo npm install -g npm@6.13.4
            - run:
                  name: 'Update Yarn'
                  command: yarn policies set-version 1.22.4
            - run:
                  name: 'Set caching variables'
                  command: |
                      LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/dev?filter=successful&limit=1"
                      LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
                      echo $LAST_SUCCESSFUL_COMMIT > /tmp/last-successful-commit
                      echo $CIRCLE_SHA1 > /tmp/current-commit
            - restore_cache:
                  keys:
                      - build-cache-{{ .Branch }}-{{ checksum "/tmp/last-successful-commit" }}
                      - build-cache-dev-{{ checksum "/tmp/last-successful-commit" }}
            - run:
                  name: 'Install Dependencies'
                  command: yarn install
            - run:
                  name: 'Build Packages'
                  command: yarn build
            - save_cache:
                  key: repo-{{ .Environment.CIRCLE_SHA1 }}
                  paths:
                      - ~/repo
            - save_cache:
                  key: build-cache-{{ .Branch }}-{{ checksum "/tmp/current-commit" }}
                  paths:
                      - ~/repo/packages/contract-artifacts/node_modules
                      - ~/repo/packages/contract-artifacts/lib
                      - ~/repo/packages/contracts/node_modules
                      - ~/repo/packages/dev-utils/node_modules
                      - ~/repo/packages/react-app/node_modules
                      - ~/repo/packages/subgraph/node_modules
    test:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10.18.1
        steps:
            - restore_cache:
                  keys:
                      - repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                  name: 'Test Packages'
                  command: yarn test

workflows:
    version: 2
    main:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore: gh-pages
            - test:
                  requires:
                      - build
                  filters:
                      branches:
                          ignore: gh-pages
